project:
  type: website
  output-dir: docs

website:
  title: "Katie Thompson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: opinion.qmd
        text: Opinion
      - href: cv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css